test.exception.with.arg=Hi there i''m an exception but with an arrrrg {0}